// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using locadora_de_carros.Data;

#nullable disable

namespace locadora_de_carros.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("locadora_de_carros.Domain.Entities.CarroEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("nr_ano");

                    b.Property<string>("Marca")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ds_marca");

                    b.Property<string>("Modelo")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ds_modelo");

                    b.Property<decimal>("ValorDiaria")
                        .HasPrecision(10, 2)
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("nr_valordiaria");

                    b.HasKey("Id");

                    b.ToTable("TB_CARRO");
                });
#pragma warning restore 612, 618
        }
    }
}
